name: flutter_hand_tracking_plugin
description: A Flutter plugin for hand tracking using advanced machine learning algorithms.
version: 0.0.1
author: Your Name <your.email@example.com>
homepage: https://github.com/yourusername/flutter_hand_tracking_plugin

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  protobuf: ^2.0.0  # Updated to a version that supports null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: xyz.zhzh.flutter_hand_tracking_plugin
        pluginClass: FlutterHandTrackingPlugin
      ios:
        pluginClass: FlutterHandTrackingPlugin
